FROM python:3.11
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt upgrade -y
RUN apt install build-essential -y
RUN apt install git -y
RUN apt install fish -y
RUN apt install iverilog verilator gtkwave -y
RUN pip3 install -U pip
RUN pip3 install pytest pytest-pythonpath
WORKDIR "/home"
RUN git clone https://github.com/PyHDI/veriloggen.git
RUN cd veriloggen && python3 setup.py install && cd ../
ENV PYTHONPATH="/home/veriloggen:${PYTHONPATH}"